name: "s3"
version: "0.8.0-hex"
usage: "The plugin allows to use s3 protocol to upload, fetch charts and to work with repositories."
description: |-
  Provides AWS S3 protocol support.
  https://github.com/hex-inc/helm-s3
command: "$HELM_PLUGIN_DIR/bin/helms3"
downloaders:
- command: "bin/helms3"
  protocols:
    - "s3"
hooks:
  install: "cd $HELM_PLUGIN_DIR; ./hack/install.sh"
  update: "cd $HELM_PLUGIN_DIR; ./hack/install.sh"
